### ISSUE TITLE
NPE when trying to open table which has null values

### ISSUE THREAD

**Issue by vitalyraevsky** [dmytrodanylyk/realm-browser#12]
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cox.ru.messenger, PID: 32300
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
            at com.dd.realmbrowser.utils.MagicUtils.invokeMethod(MagicUtils.java:34)

I`m using realm version 0.80.3

**Comment by vitalyraevsky** [comment]
maybe need more app info?

**Comment by dmytrodanylyk** [comment]
Nope, I can reproduce the issue.

**Comment by vitalyraevsky** [comment]
тоді, чекаю фікса

**Comment by dmytrodanylyk** [comment]
Fixed in version `0.0.3` should be available on Maven Central in a few hours.
