### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by dmytrodanylyk** [dmytrodanylyk/realm-browser#6]

**Comment by gcmorrison** [comment]
I added mavenCentral to my repositories, but I still can't "find" it.  Error below:

Error:A problem occurred configuring project ':myApp'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.github.dmytrodanylyk.realm-browser:0.0.2:.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          https://jcenter.bintray.com/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>          https://repo1.maven.org/maven2/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          https://repo1.maven.org/maven2/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>          http://dl.bintray.com/madcyph3r/maven/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          http://dl.bintray.com/madcyph3r/maven/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>          https://clojars.org/repo/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          https://clojars.org/repo/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>          file:/opt/android-sdk/extras/android/m2repository/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          file:/opt/android-sdk/extras/android/m2repository/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>          file:/opt/android-sdk/extras/google/m2repository/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.pom
>          file:/opt/android-sdk/extras/google/m2repository/com/github/dmytrodanylyk/realm-browser/0.0.2//0.0.2-.jar
>      Required by:
>          myApp:app:unspecified

**Comment by dmytrodanylyk** [comment]
It's available for sure: http://gradleplease.appspot.com/#realm-browser

Can u post your gradle file here?

**Comment by gcmorrison** [comment]
Thank you for the very prompt response.  I created a new empty project and
just added realm-browser.  It seems to find it correctly there.  So there's
something wrong with my main app's gradle config.  That's my bad.  Thanks
anyway :)

**Comment by gcmorrison** [comment]
Ah, wait, I found the problem!  The gradle config you provide on the main Readme is different to the one from gradleplease.

GradlePl: compile 'com.github.dmytrodanylyk.realm-browser:library:0.0.2'
Readme: compile 'com.github.dmytrodanylyk.realm-browser:0.0.2'

**Comment by dmytrodanylyk** [comment]
@gcmorrison thanks, fixed now. Don't forget to check out [User Guide](https://github.com/dmytrodanylyk/realm-browser/wiki/User-Guide).
