### ISSUE TITLE
Not show data from another module (different packagename)

### ISSUE THREAD

**Issue by alorma** [dmytrodanylyk/realm-browser#9]
Hi.

We have the wollowing structure in our project:

/
- App com.ourapp.app
- Domain com.ourapp.domain
- Data com.ourapp.data --- Where realm data is loaded and saved)

When we execute realm browser from app module, we can't see any register in the DB.

![device-2015-05-11-124246](https://cloud.githubusercontent.com/assets/887462/7563255/8a81b188-f7db-11e4-9fe1-a75b263db915.png)

FYI: If we call `RealmFilesActivity.start(this);` we can't see any file

**Comment by dmytrodanylyk** [comment]
> FYI: If we call `RealmFilesActivity.start(this);` we can't see any file

It means no file inside `getApplicationInfo().dataDir` [link](https://github.com/dmytrodanylyk/realm-browser/blob/master/realm-browser/src/main/java/com/dd/realmbrowser/RealmFilesActivity.java#L38)

Can you tell me path where your realm database is located?

**Comment by alorma** [comment]
Yes, there are file sinside dataDir, 2 files exactly:

default.realm
default.realm.lock.

We debugged, and found that isValid(String extensions) returns `false` even if it's the .realm file.
That's caused because it splits file  name into ".realm", and not "realm". ANd so the method returns false (is not in ignore list), so code after isValid is never query

**Comment by dmytrodanylyk** [comment]
Thanks, I will fix it later today and push to Maven Central new version. Thanks for help!
